version: "3"
services:
  mysql:
    image: mariadb:10.3
    networks:
      - net
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 33061:3306
  redis:
    image: redis:5
    networks:
      - net
    volumes:
      - ./data/redis:/var/lib/redis
    command: ["redis-server", "--appendonly", "yes"]
  rabbitmq:
    image: rabbitmq
    networks:
      - net
  syzoj:
    # image: syzoj/syzoj:base
    image: philogag/syzoj_for_zust:alpine-web-only
    networks:
      - net
    depends_on:
      - redis
      - mysql
    volumes:
      - ./config:/opt/config
      - ./data/syzoj:/opt/syzoj/data
    command: ["node", "/opt/syzoj/app.js", "-g", "/opt/config/web.json", "-s", "/opt/config/sql.json"]
    working_dir: "/opt/syzoj"
    ports:
      - 5283:5283
    restart: always
  judger:
    image: syzoj/syzoj:base
    # image: registry.cn-hangzhou.aliyuncs.com/philogag/syzoj:debug
    networks:
      - net
    depends_on:
      - syzoj
    volumes:
      - ./config:/opt/config
      - ./data/syzoj:/opt/syzoj/data
    working_dir: "/opt/judge-v3"
    command: ["node", "/opt/judge-v3/lib/daemon/index.js", "-c", "/opt/config/daemon.json", "-v"]
  runner:
    image: syzoj/syzoj:base     
    # image: registry.cn-hangzhou.aliyuncs.com/philogag/syzoj:debug
    networks:
      - net
    volumes:
      - ./config:/opt/config
      - ./data/syzoj:/opt/syzoj/data
      - ./sandbox-rootfs:/sandbox-rootfs
      - ./data/bin:/opt/binary
      - ./data/temp1:/opt/temp
    working_dir: "/opt/judge-v3"
    command: ["node", "/opt/judge-v3/lib/runner/index.js", "-s", "/opt/config/runner-shared.json", "-i", "/opt/config/runner-instance.json", "-v"]
    privileged: true
networks:
  net:
